#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


echo "-------------- Hive-do-component-build-started -----------"

set -ex

. `dirname ${0}`/bigtop.bom

base_path=`pwd`

# HIVE_MAVEN_OPTS=" -Dhbase.version=$HBASE_VERSION \
# -Dzookeeper.version=$ZOOKEEPER_VERSION \
# -Dhadoop.mr.rev=23 \
# -Dhadoop.security.version=$HADOOP_VERSION \
# -Dhadoop-23.version=$HADOOP_VERSION \
# -Dhbase.hadoop2.version=$HBASE_VERSION \
# -Dmvn.hadoop.profile=hadoop23 \
# -DskipTests \
# -Dhbase.version.with.hadoop.version=$HBASE_VERSION \
# -Dtez.version=${TEZ_VERSION} \
# -Dspark.version=${SPARK1_VERSION}
# "

HIVE_MAVEN_OPTS=" -Dhbase.version=2.0.2 \
-Dzookeeper.version=3.4.6 \
-Dhadoop.mr.rev=23 \
-Dhadoop.security.version=3.1.1 \
-Dhadoop-23.version=3.1.1 \
-Dhbase.hadoop2.version=2.0.2 \
-Dmvn.hadoop.profile=hadoop23 \
-DskipTests \
-Dhbase.version.with.hadoop.version=2.0.2 \
-Dtez.version=0.9.1 \
-Dspark.version=2.4.0
"

export MAVEN_OPTS="-Xmx1500m -Xms1500m"
mvn -T 2.0C ${HIVE_MAVEN_OPTS} clean install -Phadoop-2,dist "$@"

rm -fr build && mkdir build

echo " doing untar hive"

tar -C build --strip-components=1 -xzf packaging/target/apache-hive-${HIVE_VERSION}-bin.tar.gz

# save components`s .bin package
tar -zcvf hive-$HIVE_VERSION-bin.tar.gz build/
mv hive-$HIVE_VERSION-bin.tar.gz ../../../tar/