#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


echo "-------------- Oozie-do-component-build-started -----------"

set -ex

. `dirname ${0}`/bigtop.bom

base_path=`pwd`


export MAVEN_OPTS="-Xmx4500m -Xms4500m"

./bin/mkdistro.sh -DskipTests -Phadoop-3 -Puber

rm -fr build && mkdir build

tar -C build --strip-components=1 -xzf distro/target/oozie-${OOZIE_VERSION}-distro.tar.gz

cd build && mv oozie-sharelib-${OOZIE_VERSION}.tar.gz oozie-sharelib.tar.gz 

tar -zxf oozie-sharelib.tar.gz
tar -zxf oozie-client-${OOZIE_VERSION}.tar.gz && rm -fr oozie-client-${OOZIE_VERSION}.tar.gz && mv oozie-client-${OOZIE_VERSION} oozie-client
unzip -q docs.zip && rm -fr docs.zip

mkdir webapps && unzip -q oozie.war -d ./webapps/

cd ./bin/ && mv oozie oozie.distro && mv oozied.sh oozied.distro

wrapper=oozie
install -d -m 0755 `dirname $wrapper`
cat > $wrapper <<EOF
#!/bin/bash
export ANYSCALE_VERSION=${ANYSCALE_VERSION:-1-0-0-0-108}
export OOZIE_CLIENT_OPTS="-Danyscale.version=${ANYSCALE_VERSION} ${OOZIE_CLIENT_OPTS}
exec /opt/anyscale/1.0.0.0-108/oozie/bin/oozie.distro "$@"
EOF
chmod 755 $wrapper

wrapper=oozied.sh
install -d -m 0755 `dirname $wrapper`
cat > $wrapper <<EOF
#!/bin/bash
export ANYSCALE_VERSION=${ANYSCALE_VERSION:-1-0-0-0-108}
export CATALINA_OPTS="-Danyscale.version=${ANYSCALE_VERSION} ${CATALINA_OPTS}"
exec /opt/anyscale/1.0.0.0-108/oozie/bin/oozied.distro "$@"
EOF
chmod 755 $wrapper

cd ../../