#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


echo "-------------- Tez-do-component-build-started -----------"

set -xe

. `dirname $0`/bigtop.bom

base_path=`pwd`

sed  -i "s|<hadoop.version>.*</hadoop.version>|<hadoop.version>3.1.1</hadoop.version>|" pom.xml
sed -i "/bower install/{n;n;s/install/install --allow-root --remove-unnecessary-resolutions=false/g}" tez-ui/pom.xml

mvn clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -DskipTests=true -Phadoop31 -Dtar -Dhadoop.version=${HADOOP_VERSION}
rm -fr build && mkdir build

echo " doing untar tez"
tar -C build --strip-components=1 -xzf ${base_path}/tez-dist/target/tez-$TEZ_VERSION-minimal.tar.gz
cp ${base_path}/tez-dist/target/tez-$TEZ_VERSION.tar.gz build/lib

# save components`s .bin package
tar -zcvf tez-$TEZ_VERSION.tar.gz build/
mv tez-$TEZ_VERSION.tar.gz ../../../tar/

echo "-------------- Tez-do-component-build-completed --------------"
