#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## http://central.maven.org/maven2/org/apache/hive/hive-standalone-metastore/3.1.1/

echo "-------------- Spark2-do-component-build-started -----------"

set -ex

. `dirname $0`/bigtop.bom

#./dev/make-distribution.sh --name jdp-spark --tgz --pip \
# --r \
#-Psparkr -Phadoop-3.1 -Phive -Phive-thriftserver -Pmesos -Pyarn -Pkubernetes -DskipTests

cp -r /ws/jdp-package/dl/spark2-2.4.0-src/* ./

tar -zxvf spark-2.4.0-bin-jdp-spark.tgz
cd spark-2.4.0-bin-jdp-spark && mkdir standalone-metastore && cd standalone-metastore &&  wget http://central.maven.org/maven2/org/apache/hive/hive-standalone-metastore/3.1.1/hive-standalone-metastore-3.1.1.jar
cd ../../

rm -fr dist  && mv spark-2.4.0-bin-jdp-spark dist
mv spark-2.4.0-bin-jdp-spark.tgz ../../../tar/

echo "-------------- Spark2-do-component-build-end -----------"