#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

echo "-------------- ClickHouse-do-component-build-started -----------"

base_path=`pwd`

echo "current path: ${base_path}"

. `dirname $0`/bigtop.bom

# Basic environment
export CMAKE=cmake3
export CC=/opt/rh/devtoolset-9/root/usr/bin/gcc
export CXX=/opt/rh/devtoolset-9/root/usr/bin/g++

# Detect number of threads to run 'make' command
export THREADS=$(grep -c ^processor /proc/cpuinfo)

# CMAKE_BUILD_TYPE = Release、Debug、RelWithDebugInfo、MinSizeRel
export CMAKE_BUILD_TYPE=Release

echo "CMAKE=$CMAKE"
echo "CC=$CC"
echo "CXX=$CXX"
echo "THREADS=$THREADS"

echo "CentOS 7 has some special CMAKE_OPTIONS"
CMAKE_OPTIONS="${CMAKE_OPTIONS} -DGLIBC_COMPATIBILITY=OFF"
CMAKE_OPTIONS="${CMAKE_OPTIONS} -DNO_WERROR=1"
# Starting with v20.3 there is new option to tolerate warnings
CMAKE_OPTIONS="${CMAKE_OPTIONS} -DWERROR=0"

# Build clickhouse rdbms
rm -rf build
mkdir build
cd build
echo ${soft_package_version}
$CMAKE .. -DCMAKE_INSTALL_PREFIX=/opt/anyscale/1.0.0.0-108/clickhouse -DCMAKE_BUILD_TYPE:STRING="${CMAKE_BUILD_TYPE}" ${CMAKE_OPTIONS}
make -j $THREADS
cd ..

echo "-------------- ClickHouse-do-component-build-completed --------------"