#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "-------------- Superset-do-component-build-started -----------"

set -ex

base_path=`pwd`

echo "current path: ${base_path}"

. `dirname $0`/bigtop.bom

# Install system package
sudo yum install gcc gcc-c++ libffi-devel python-devel python-pip python-wheel openssl-devel openldap-devel mysql-devel postgresql-devel -y
# TODO: node version is too low recommended upgrade version
# wget https://nodejs.org/download/release/v8.9.4/node-v8.9.4-linux-x64.tar.gz
# tar -zxf node-v8.9.4-linux-x64.tar.gz -C /usr/local
# rm -f /usr/local/node
# ln -s /usr/local/node-v8.9.4-linux-x64 /usr/local/node
# rm -f node-v8.9.4-linux-x64.tar.gz

# Install virtualenv && Create python virtual environment
pip install virtualenv
mkdir -p /usr/jdp/current
virtualenv /usr/jdp/current/superset

# Into the Python virtual environment
source /usr/jdp/current/superset/bin/activate

# Build superset core and assets 
# TODO: support python in 2.7 | 3.x not working
cd superset/assets/

sh ./js_build.sh

cd ../../

python setup.py install

# Here’s a list of some of the recommended packages.
pip install sqlalchemy-clickhouse
pip install mysqlclient
pip install impyla
pip install pyhive
pip install psycopg2
pip install PyMySQL
pip install PyGreSQL

mkdir -p build/superset && cp -r /usr/jdp/current/superset/* build/superset/

# save components`s .bin package
tar -zcf superset-$SUPERSET_VERSION-bin.tar.gz build/
mv superset-$SUPERSET_VERSION-bin.tar.gz ../../../tar/

echo "-------------- Superset-do-component-build-completed --------------"