#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "-------------- Streamline-do-component-build-started -----------"

set -ex

. `dirname ${0}`/bigtop.bom

base_path=`pwd`

echo "current path: ${base_path}"

# Generate build  
rm -rf build
mkdir build

# "Build knox"
# mvn -Ppackage -DskipTests=true clean install

# Generate binary package
tar -zxvf /ws/jdp-package/dl/knox-1.0.0-src/target/${KNOX_VERSION}/knox-${KNOX_VERSION}.tar.gz --strip-components 1 -C build

echo "-------------- Streamline-do-component-build-completed --------------"